#pragma once

#define STREAM_FILE 0
#define STREAM_TCP 1
#define STREAM_UDP 2
#define STREAM_BLUETOOTH 3
#define STREAM_BT STREAM_BLUETOOTH
#define STREAM_IR 4
#define STREAM_SMS 5
#define STREAM_CABLE 6
#define STREAM_RESOURCE 7
#define STREAM_HTTP 8
#define STREAM_BT_MULTI 9

#define STREAM_READ 0x0100
#define STREAM_WRITE 0x0200
#define STREAM_READWRITE (STREAM_READ|STREAM_WRITE)
#define STREAM_BINARY 0x0400
#define STREAM_TEXT 0x0000
#define STREAM_CREATE 0x0800
#define STREAM_TRUNC 0x1000
#define STREAM_EXCL 0x2000
#define STREAM_DELETE 0x4000
#define STREAM_ACCEPT 0x8000
#define STREAM_OBEX 0x0400
#define STREAM_MODE_MASK 0xFF00
#define STREAM_PORT_SHIFT 16


struct StreamSlot {
	FILE* fd;
};