#include "input.h"

Input::Input()
{
	keys[KEYUP] = SDL_SCANCODE_UP;
	keys[KEYDOWN] = SDL_SCANCODE_DOWN;
	keys[KEYLEFT] = SDL_SCANCODE_LEFT;
	keys[KEYRIGHT] = SDL_SCANCODE_RIGHT;
	keys[KEYFIRE] = SDL_SCANCODE_LCTRL;
	keys[KEYFIRE2] = SDL_SCANCODE_SPACE;
	keys[KEYSELECT] = SDL_SCANCODE_RETURN;
	keys[POINTERDOWN] = SDL_SCANCODE_LSHIFT;
	keys[POINTERALTDOWN] = SDL_SCANCODE_LALT;
}

Input::~Input()
{

}